//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Ado.Net.Edm_model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities1 : DbContext
    {
        public Database1Entities1()
            : base("name=Database1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgeRestriction> AgeRestriction { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Films> Films { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<Halls> Halls { get; set; }
        public virtual DbSet<Plases> Plases { get; set; }
        public virtual DbSet<Session> Session { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
    }
}
