//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Ado.Net.Edm_model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int PlaceId { get; set; }
        public int SessionId { get; set; }
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
